server {
    server_name comprai.2.25.122.11.nip.io;

    # Servir arquivos estáticos do K6 diretamente
    location /k6/ {
        alias /var/www/html/k6/;
        try_files $uri $uri/ =404;
    }

    location / {
        proxy_pass http://localhost:5020;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_read_timeout 300s;
    }

    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/comprai.2.25.122.11.nip.io/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/comprai.2.25.122.11.nip.io/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = comprai.2.25.122.11.nip.io) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

    server_name comprai.2.25.122.11.nip.io;
    listen 80;
    return 404; # managed by Certbot
}